//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCardReader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageConsts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageConsts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VCardReader.Localization.LanguageConsts", typeof(LanguageConsts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        internal static string AssistantLabel {
            get {
                return ResourceManager.GetString("AssistantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        internal static string AssistantTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("AssistantTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pager.
        /// </summary>
        internal static string BeeperTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("BeeperTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string BirthdayLabel {
            get {
                return ResourceManager.GetString("BirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business fax.
        /// </summary>
        internal static string BusinessFaxNumberLabel {
            get {
                return ResourceManager.GetString("BusinessFaxNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business 2.
        /// </summary>
        internal static string BusinessTelephoneNumber2Label {
            get {
                return ResourceManager.GetString("BusinessTelephoneNumber2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        internal static string BusinessTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("BusinessTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback.
        /// </summary>
        internal static string CallbackTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("CallbackTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        internal static string CarTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("CarTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string CellularTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("CellularTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy.
        /// </summary>
        internal static string DataFormat {
            get {
                return ResourceManager.GetString("DataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string DataFormatWithTime {
            get {
                return ResourceManager.GetString("DataFormatWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string DepartmentLabel {
            get {
                return ResourceManager.GetString("DepartmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string DisplayNameLabel {
            get {
                return ResourceManager.GetString("DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail display as.
        /// </summary>
        internal static string Email1DisplayNameLabel {
            get {
                return ResourceManager.GetString("Email1DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email1EmailAddressLabel {
            get {
                return ResourceManager.GetString("Email1EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 2 display as.
        /// </summary>
        internal static string Email2DisplayNameLabel {
            get {
                return ResourceManager.GetString("Email2DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 2.
        /// </summary>
        internal static string Email2EmailAddressLabel {
            get {
                return ResourceManager.GetString("Email2EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 3 display as.
        /// </summary>
        internal static string Email3DisplayNameLabel {
            get {
                return ResourceManager.GetString("Email3DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail 3.
        /// </summary>
        internal static string Email3EmailAddressLabel {
            get {
                return ResourceManager.GetString("Email3EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string GivenNameLabel {
            get {
                return ResourceManager.GetString("GivenNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home address.
        /// </summary>
        internal static string HomeAddressLabel {
            get {
                return ResourceManager.GetString("HomeAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home fax.
        /// </summary>
        internal static string HomeFaxNumberLabel {
            get {
                return ResourceManager.GetString("HomeFaxNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home 2.
        /// </summary>
        internal static string HomeTelephoneNumber2Label {
            get {
                return ResourceManager.GetString("HomeTelephoneNumber2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("HomeTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string ImportanceHighText {
            get {
                return ResourceManager.GetString("ImportanceHighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        internal static string ImportanceLabel {
            get {
                return ResourceManager.GetString("ImportanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string ImportanceLowText {
            get {
                return ResourceManager.GetString("ImportanceLowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImportanceNormalText {
            get {
                return ResourceManager.GetString("ImportanceNormalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IM address.
        /// </summary>
        internal static string InstantMessagingAddressLabel {
            get {
                return ResourceManager.GetString("InstantMessagingAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDN.
        /// </summary>
        internal static string ISDNNumberLabel {
            get {
                return ResourceManager.GetString("ISDNNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string OrganizationLabel {
            get {
                return ResourceManager.GetString("OrganizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company main phone.
        /// </summary>
        internal static string OrganizationMainTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("OrganizationMainTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other address.
        /// </summary>
        internal static string OtherAddressLabel {
            get {
                return ResourceManager.GetString("OtherAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other fax.
        /// </summary>
        internal static string OtherFaxLabel {
            get {
                return ResourceManager.GetString("OtherFaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("OtherTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other fax.
        /// </summary>
        internal static string PrimaryFaxNumberLabel {
            get {
                return ResourceManager.GetString("PrimaryFaxNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary phone.
        /// </summary>
        internal static string PrimaryTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("PrimaryTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        internal static string RadioTelephoneNumberLabel {
            get {
                return ResourceManager.GetString("RadioTelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse/Partner.
        /// </summary>
        internal static string SpouseNameLabel {
            get {
                return ResourceManager.GetString("SpouseNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telex.
        /// </summary>
        internal static string TelexNumberLabel {
            get {
                return ResourceManager.GetString("TelexNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTY/TDD phone.
        /// </summary>
        internal static string TextTelephoneLabel {
            get {
                return ResourceManager.GetString("TextTelephoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        internal static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page.
        /// </summary>
        internal static string WebpageDefaultLabel {
            get {
                return ResourceManager.GetString("WebpageDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal webpage.
        /// </summary>
        internal static string WebpagePersonalLabel {
            get {
                return ResourceManager.GetString("WebpagePersonalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work webpage.
        /// </summary>
        internal static string WebPageWorkLabel {
            get {
                return ResourceManager.GetString("WebPageWorkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary.
        /// </summary>
        internal static string WeddingAnniversaryLabel {
            get {
                return ResourceManager.GetString("WeddingAnniversaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address.
        /// </summary>
        internal static string WorkAddressLabel {
            get {
                return ResourceManager.GetString("WorkAddressLabel", resourceCulture);
            }
        }
    }
}
